### ISSUE TITLE
Other plugins?

### ISSUE THREAD

**Issue by mattrobenolt** [lincolnloop/pyuwsgi-wheels#6]
I’m not entirely sure the plans here, but could we have an opinionated bundle that includes extra plugins? Since installing them is non-trivial and with pyuwsgi, we aren’t able to compile and install new ones. 

In all of our projects, we like to use uwsgi-dogstatsd. But I now don’t have a great way to pull that in, so having to revert back to plain old uWSGI. 

Asking because I see there was a decision to precompile the statsd module already which is not done by default.

**Comment by ipmb** [comment]
Hey @mattrobenolt sorry I missed the notification on your issue.

Have you tried using the statsd plugin with Datadog? I remember looking at this a while back and iirc, there is no functional difference when it comes to uWSGI.

**Comment by ipmb** [comment]
The thought process with adding statsd was selfish (I needed it to send stats to Datadog too) and I justified it because gunicorn includes statsd too.

I'm not interested in maintaining an additional package with other plugins, but it's easy if you want to fork. We already have a script that is used to setup a custom build profile: https://github.com/lincolnloop/pyuwsgi-wheels/blob/master/patch-uwsgi-packaging.sh#L11-L12

**Comment by mattrobenolt** [comment]
We just compile in the dogstatsd plugin. :) For example: https://github.com/getsentry/snuba/blob/master/Dockerfile#L67-L74

The dogstatsd utilizes tags properly which the statsd plugin doesn’t. It’s a minor difference, but is nice QOL improvement.
